//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Finale
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctor_data()
        {
            this.appointment_data = new HashSet<appointment_data>();
        }
    
        public string doctor_id { get; set; }
        public string doctor_name { get; set; }
        public string speciality_name { get; set; }
        public string visiting_hrs { get; set; }
        public string education { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment_data> appointment_data { get; set; }
        public virtual speciality_data speciality_data { get; set; }
    }
}
