//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Finale
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_table
    {
        public string login_id { get; set; }
        public string login_password { get; set; }
    }
}
