//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Finale
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDAC_POLDEntities : DbContext
    {
        public CDAC_POLDEntities()
            : base("name=CDAC_POLDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointment_data> appointment_data { get; set; }
        public virtual DbSet<doctor_data> doctor_data { get; set; }
        public virtual DbSet<login_table> login_table { get; set; }
        public virtual DbSet<patient_data> patient_data { get; set; }
        public virtual DbSet<speciality_data> speciality_data { get; set; }
        public virtual DbSet<reception_view> reception_view { get; set; }
        public virtual DbSet<specialities_view> specialities_view { get; set; }
        public virtual DbSet<appointment_id_factory> appointment_id_factory { get; set; }
    }
}
