//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Finale
{
    using System;
    using System.Collections.Generic;
    
    public partial class reception_view
    {
        public string appointment_id { get; set; }
        public string patient_name { get; set; }
        public string doctor_name { get; set; }
        public System.DateTime appointment_date { get; set; }
        public string appointment_status { get; set; }
        public string speciality_name { get; set; }
        public string visiting_hrs { get; set; }
        public string doctor_id { get; set; }
        public long mobile_no { get; set; }
    }
}
